apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-lgtm
  namespace: sidecar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-lgtm
  template:
    metadata:
      labels:
        app: otel-lgtm
    spec:
      containers:
        - name: otel-lgtm
          image: grafana/otel-lgtm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana
              containerPort: 3000
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  namespace: sidecar-demo
spec:
  selector:
    app: otel-lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
  type: ClusterIP
