apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-sidecar-config
  namespace: sidecar-demo
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch: {}
    exporters:
      debug:
        verbosity: detailed
      otlp/remote:
        endpoint: otel-lgtm.sidecar-demo.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/remote]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/remote]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/remote]
